### ISSUE TITLE
Нарушения SOLID и другого

### ISSUE THREAD

**Issue by Naabway1** [HukuTa45/HomeWork363#1]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/SecondExample.cs#L31C9-L31C71
В данном случае происходит нарушение метода Лисков, создается исключение, которое приводит к неустойчивости кода. В данном случае throw new ... можно заменить на Console.WriteLine(...), тогда и нарушения метода Лисков не будет, и сам метод выполнится как нужно было.

**Comment by Naabway1** [comment]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/SecondExample.cs#L21C5-L21C36
Не уверен, что это нарушает какой-то из принципов, но нейминг странный :), в данном случае каждый класс наследуется от класса Animal и переписывается существующий метод MakeSound(). В этом же классе создается новый метод MakeMeow(), что не несет какого-либо смысла, когда можно переписать уже существующий MakeSound().

**Comment by Naabway1** [comment]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/ThirdExample.cs#L3C1-L19C6 использование транскрипции является нарушением нейминга, как и использование символьных сокращений, что делает код менее читаемым(переименовать PP и platezhka в PaymentProcess и payment соответственно). Также, в данном случае идет нарушение принципа открытости/закрытости, код не добавляется, а модифицируется уже существующий. Плюс идет нарушение принципа единственной ответственности (как мне кажется), так как в одном классе описываются методы для уже других платежных систем.

Можно попробовать исправить:
Создание класса:
public abstract class PaymentProcess {...}

Изменение конструктора(?) этого класса на абстрактный метод:
public abstract decimal PayProc(); //если честно, не особо понимаю как здесь метод назвать xD

После создавать классы, наследующиеся от PaymentProcess и там прописывать логику методов и то, что они должны возвращать.

**Comment by Naabway1** [comment]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/ThirdExample.cs#L11C1-L14C10 не понимаю причем здесь Мир и ПейПал, разные системы абсолютно.

**Comment by Naabway1** [comment]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/ThirdExample.cs#L21C1-L21C66 Проблема нейминга, выше описывал что нужно делать в таком случае

**Comment by Naabway1** [comment]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/FirstExample.cs#L5
Нарушение принципа инверсии зависимости. Данный класс зависит от низкоуровнегого класса. Создать абстрактный класс  MessageService (если это интерфейс, то букву I в начале имени класса добавить) с методом SendEmail. Далее классы Notification и EmailService наследовать от MessageService и переписывать методы отправки сообщения в зависимости от их зоны применения.

**Comment by HukuTa45** [comment]
1. 

> Не уверен, что это нарушает какой-то из принципов, но нейминг странный :), в данном случае каждый класс наследуется от класса Animal и переписывается существующий метод MakeSound(). В этом же классе создается новый метод MakeMeow(), что не несет какого-либо смысла, когда можно переписать уже существующий MakeSound().

>  В данном случае происходит нарушение метода Лисков, создается исключение, которое приводит к неустойчивости кода. В данном случае throw new ... можно заменить на Console.WriteLine(...), тогда и нарушения метода Лисков не будет, и сам метод выполнится как нужно было.

Если делать совсем по умному, без нарушения принципов. Нужно вынести рыбу в отдельный класс, который не будет переопределять метод MakeSound, или создать новый интерфейс для животных, которые не могут издавать звуки. 
throw new в данном контексте задания это корректное поведение, ты прокидываешь ошибку потому что рыбы не разговаривают, а не информируешь в консоли об ошибке. Ошибку можно обрабатывать в дальнейшем, запись в консоль ты не сможешь отловить. (Если вообще упороться и юзать потоки с `cancellationToken` то исключение тебе поможет вывести ошибку в лог, при этом не роняя весь сервис)





2.

> https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/ThirdExample.cs#L3C1-L19C6 использование транскрипции является нарушением нейминга, как и использование символьных сокращений, что делает код менее читаемым(переименовать PP и platezhka в PaymentProcess и payment соответственно). Также, в данном случае идет нарушение принципа открытости/закрытости, код не добавляется, а модифицируется уже существующий. Плюс идет нарушение принципа единственной ответственности (как мне кажется), так как в одном классе описываются методы для уже других платежных систем.
> 
> Можно попробовать исправить: Создание класса: public abstract class PaymentProcess {...}
> 
> Изменение конструктора(?) этого класса на абстрактный метод: public abstract decimal PayProc(); //если честно, не особо понимаю как здесь метод назвать xD
> 
> После создавать классы, наследующиеся от PaymentProcess и там прописывать логику методов и то, что они должны возвращать.

Нейминг - да. Нарушение открытости/закрытости - да. 
Каждый тип платежа должен быть отдельным классом, наследующим базовый класс PaymentMethod, и каждый класс должен иметь метод для обработки платежа. Таким образом, добавление нового способа оплаты не потребует изменения существующего кода.

3.
> https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/FirstExample.cs#L5
> 
> 
> Нарушение принципа инверсии зависимости. Данный класс зависит от низкоуровнего класса. Создать абстрактный класс MessageService (если это интерфейс, то букву I в начале имени класса добавить) с методом SendEmail. Далее классы Notification и EmailService наследовать от MessageService и переписывать методы отправки сообщения в зависимости от их зоны применения.

Ввести интерфейс IMessageService и сделать так, чтобы Notification зависел от абстракции, а не от конкретной реализации. Нужно создавать классы, которые наследуются от интерфейса.
Приведу пример:
У тебя есть проект на 100500 различных классов и методов. И тут ты в одном моменте решаешь, что вот в этом месте у тебя метод, в этом классе должен принимать не int, а string. Из-за того что у тебя класс завязан на интерфейс ты сразу увидишь ошибку, пойдешь менять в интерфейсе, увидишь где еще у тебя в программе используется этот же метод, поправишь.

Если ты делаешь класс, который не зависит ни от какого интерфейса, но используется много где то подобные изменения могут сломать логику в другом месте
