### ISSUE TITLE
Замечания по ООП и принципам SOLID

### ISSUE THREAD

**Issue by Kenotgg** [HukuTa45/HomeWork363#5]
https://github.com/HukuTa45/HomeWork363/blob/a799518340267c6510e84def1ebcfcbfd0a98226/ConsoleApp1/FirstExample.cs#L9 
**Замечание По SOLID**
Нарушение принципа инверсии зависимостей(Dependency inversion Principle) Класс Notification напрямую зависит от EmailService, что является проблемой при тестировании и замене реализации сервиса.

**Comment by Kenotgg** [comment]
**Замечание по SOLID:**
Второй файл строка 31, (I — Interface Segregation Principle,  так как Fish берет не нужный для нее функционал).

**Comment by Kenotgg** [comment]
**Третий файл, непонятный некорректный нейминг к примеру - plateshka, PP, замечания по ООП и принципам SOLID.**
строка 7,11 - нарушение принципа  O — Open/Closed Principle, так как приходится модифицировать класс PP для того чтобы внести новый тип карты.
строка 21 - не стоит называть объект kreditka, лучше назвать его creditCard.
строка 7, 11, - Paypal скорее является наследником CreditCard а не равнозначным объектом.
21,27 - отдельный метод под каждую платежную систему, (по идее класс вообще не должен знать что за карту он обрабатывает).
В классе нарушен Принцип подстановки Лисков, (Похоже что класс должен получать некую creditCard, обращаться к ее методу, а после этого уже программа поймет что за карта пришла и обратится именно к нужному методу обработки транзакции).
Строка 17- будет ли обрабатываться ошибка, если нету блоков try,catch?

**Comment by HukuTa45** [comment]
> **Третий файл, непонятный некорректный нейминг к примеру - plateshka, PP, замечания по ООП и принципам SOLID.** строка 7,11 - нарушение принципа O — Open/Closed Principle, так как приходится модифицировать класс PP для того чтобы внести новый тип карты. строка 21 - не стоит называть объект kreditka, лучше назвать его creditCard. строка 7, 11, - Paypal скорее является наследником CreditCard а не равнозначным объектом. 21,27 - отдельный метод под каждую платежную систему, (по идее класс вообще не должен знать что за карту он обрабатывает). В классе нарушен Принцип подстановки Лисков, (Похоже что класс должен получать некую creditCard, обращаться к ее методу, а после этого уже программа поймет что за карта пришла и обратится именно к нужному методу обработки транзакции). Строка 17- будет ли обрабатываться ошибка, если нету блоков try,catch?

Каждый тип платежа должен быть отдельным классом, наследующим базовый класс PaymentMethod, и каждый класс должен иметь метод для обработки платежа. Таким образом, добавление нового способа оплаты не потребует изменения существующего кода.

> **Замечание по SOLID:** Второй файл строка 31, (I — Interface Segregation Principle, так как Fish берет не нужный для нее функционал).

Если делать совсем по умному, без нарушения принципов. Нужно вынести рыбу в отдельный класс, который не будет переопределять метод MakeSound, или создать новый интерфейс для животных, которые не могут издавать звуки.

Еще был момент 
В этом же классе создается новый метод MakeMeow(), что не несет какого-либо смысла, когда класс должен переписать уже существующий MakeSound().

**Comment by HukuTa45** [comment]
> В классе нарушен Принцип подстановки Лисков, (Похоже что класс должен получать некую creditCard, обращаться к ее методу, а после этого уже программа поймет что за карта пришла и обратится именно к нужному методу обработки транзакции).

Неправильно) Нарушение принципа открытости/закрытости 
Либо я не совсем понял ход твоих мыслей, ты же отписал что 

> 
нарушение принципа O — Open/Closed Principle
